### PR TITLE
Neigbourhood

### PR DESCRIPTION
**Pull request by vdorr**
this adds handling of eRTM_NEWNEIGH, eRTM_DELNEIGH, eRTM_GETNEIGH messages

### CODE REVIEW

**Comment by Ongy** [comment]
Looks good so far, just one (maybe non-trivial) thing to change:

The definitions should not be inline in this file, but are generated by my [generator scripts](https://github.com/Ongy/netlink-hs/tree/master/Scripts).

To be honest, I haven't looked at this in a while, so I'm not 100% sure where they should go, it's probably fine to throw them into the main generator.

If you can get them set up and run them once that would be cool.
Looking at the current state (especially considering that I like new-build) I have to sanitize them soon either way, so if they are giving you troubles, just remind me about fixing up a flag in the `.cabal` file that makes it easy to compile them.

**Edit:** Also please don't close and recreate pull requests, you can update a pull request by simply pushing to the branch you created it from. This gives a better history of what happened.

**Comment by Ongy** [comment]
I have pushed a new version to the master which contains the proper sections in `netlink.cabal` to build the generator scripts.
You have to build the package with the `Generators` flag enabled, then they will be build.

Either `cabal configure -f Generators` (iirc) or `cabal new-build -f Generators` will do the trick.

**Comment by vdorr** [comment]
Generator worked well and cabal build works just fine locally, all i see on travis is caterpillar, so at this point i have no idea about failure of its checks.

**Comment by Ongy** [comment]
That was introduced by my new `netlink.cabal` file, it's an issue with older cabal and the way I default the generators to not build.

This is my TODO, your code is fine. I merged it.

**Pull request merged**
